version: '3.5'

services:
  web:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "docker"
      MYSQL_DATABASE: "klik_database"
